### ISSUE TITLE
Proguard issue

### ISSUE THREAD

**Issue by fast4x** [dead8309/KizzyRPC#14]
Hi, i've an issue with release build rpc don't work, rather with debug build it work perfectly.
I've tried to add proguard rules but without success.

Error received in release version is

WebSocket opened successfully with handshake data: A9.b@d2ba268
Received message: {"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["[\"gateway-prd-us-east1-b-d9mk\",{\"micros\":0.0}]"]}}
onError() called with: e = java.lang.IllegalStateException: TypeToken must be created with a type argument: new TypeToken<...>() {}; When using code shrinkers (ProGuard, R8, ...) make sure that generic signatures are preserved.
Closed with: code = 1000, reason = , remote = false
onError() called with: e = java.lang.RuntimeException: Invalid

Can help me please?

**Comment by dead8309** [comment]
You can try these proguard rules 
```
# Keep no-args constructor of classes which can be used with @JsonAdapter
# By default their no-args constructor is invoked to create an adapter instance
-keepclassmembers class * extends com.google.gson.TypeAdapter {
  <init>();
}
-keepclassmembers class * implements com.google.gson.TypeAdapterFactory {
  <init>();
}
-keepclassmembers class * implements com.google.gson.JsonSerializer {
  <init>();
}
-keepclassmembers class * implements com.google.gson.JsonDeserializer {
  <init>();
}

# Keep fields annotated with @SerializedName for classes which are referenced.
# If classes with fields annotated with @SerializedName have a no-args
# constructor keep that as well. Based on
# https://issuetracker.google.com/issues/150189783#comment11.
# See also https://github.com/google/gson/pull/2420#discussion_r1241813541
# for a more detailed explanation.
-if class *
-keepclasseswithmembers,allowobfuscation class <1> {
  @com.google.gson.annotations.SerializedName <fields>;
}
-if class * {
  @com.google.gson.annotations.SerializedName <fields>;
}
-keepclassmembers,allowobfuscation,allowoptimization class <1> {
  <init>();
}
```
or even upgrade gson to `2.11.0` or above

**Comment by fast4x** [comment]
Work perfectly, thanks a lot.
