### ISSUE TITLE
Images not displayed

### ISSUE THREAD

**Issue by fast4x** [dead8309/KizzyRPC#15]
Hi, I have done several tests with the images sent, I noticed that they are never displayed in Discord. 

`assets = Assets(
                largeImage = "https://i.ytimg.com/vi/${mediaItem.mediaId}/maxresdefault.jpg",
                smallImage = "https://i.ytimg.com/vi/${mediaItem.mediaId}/maxresdefault.jpg",
                largeText = mediaItem.mediaMetadata.title.toString(),
                smallText = mediaItem.mediaMetadata.artist.toString(),
            ),`

or

`assets = Assets(
                largeImage = "mp:largeimage_name",
                smallImage = "mp:smallimage_name",
                largeText = mediaItem.mediaMetadata.title.toString(),
                smallText = mediaItem.mediaMetadata.artist.toString(),
            ),`

in both method image on Discord is not displayed.

Could you help me figure out what I’m doing wrong?

Thanks in advance

**Comment by dead8309** [comment]
You can only use discord assets links so you have to 
1. Upload an image to any discord channel and grab it's link
2. remove everything before `attachments/____/_____` and
3. Use it like this `mp:attachments/____/_____`

Eg: 
`https://media.discordapp.net/attachments/1009061802593763398/1292336417795604571/1728187411154.png?ex=67035d94&is=67020c14&hm=3a94a5566e39b798089350e140e239ceec6c099f7bab4e6bdfa8f5547c2b6b40&`

Will be converted to 
`mp:attachments/1009061802593763398/1292336417795604571/1728187411154.png?ex=67035d94&is=67020c14&hm=3a94a5566e39b798089350e140e239ceec6c099f7bab4e6bdfa8f5547c2b6b40&`

**Comment by fast4x** [comment]
Thanks
