### ISSUE TITLE
rpc.close() does not end the actvity

### ISSUE THREAD

**Issue by Sajeg** [dead8309/KizzyRPC#16]
First of all I want to thank you for your library it's very useful. However I noticed that `rpc.close()` closes the websocket, but the actvity doesn't end. 
Is this a issue on my end or from this library? I hope you can help me or fix this.

**Comment by dead8309** [comment]
Thanks!! 

It takes around 30-40seconds on discord to reflect the changes automatically, if you refresh your discord the activity is gone immediately.

**Comment by Sajeg** [comment]
Oh yeah right sorry. Was totally my bad. Thank you for your fast response.
