### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MAJigsaw77** [dead8309/KizzyRPC#5]
if i want to update the rcp, i need to close the rcp first or?

**Comment by Anik200** [comment]
Gimme link plzz

**Comment by dead8309** [comment]
> if i want to update the rcp, i need to close the rcp first or?

Yea you would have to close the rpc first then pass in the new configs

**Comment by Anik200** [comment]
Give link of the apk plz bhai

**Comment by dead8309** [comment]
> Give link of the apk plz bhai

This is the RPC .what do you want in extra ?

**Comment by Anik200** [comment]
I mean i know all about this but i can't find the link of the app i even
joined discord

**Comment by dead8309** [comment]
> I mean i know all about this but i can't find the link of the app i even joined discord

Ping me on discord yzziK#3050

**Comment by MAJigsaw77** [comment]
> > if i want to update the rcp, i need to close the rcp first or?
> 
> Yea you would have to close the rpc first then pass in the new configs

Thanks for the information, I appreciate it.
